# yaml-language-server: $schema=./devcenter.schema.json

orgName: azd
environmentTypes:
  - name: Dev
    tags:
      env: dev
  - name: Test
    tags:
      env: test
  - name: Prod
    tags:
      env: prod
catalogs:
  - name: Example
    repo: https://github.com/microsoft/devcenter-catalog.git
    branch: main
    path: /Environment-Definitions/ARMTemplates
    secretIdentifier: ""
  - name: wbreza
    repo: https://github.com/wbreza/azd-devcenter-catalog.git
    branch: main
    path: /EnvironmentDefinitions
    secretIdentifier: "https://kv-o2pst6gaydv5o.vault.azure.net/secrets/dc-azd-o2pst6gaydv5o-pat-token"
projects:
  - name: Project-1
    members: []
    environmentTypes:
      - name: Dev
        deploymentTargetId: ""
        roles: ["Owner"]
        members: []
        tags:
          project: Project-1
      - name: Test
        deploymentTargetId: ""
        roles: ["Contributor"]
        members: []
        tags:
          project: Project-1
      - name: Prod
        deploymentTargetId: ""
        roles: ["Reader"]
        members: []
        tags:
          project: Project-1
  - name: Project-2
    members: []
    environmentTypes:
      - name: Dev
        deploymentTargetId: ""
        roles: ["Owner"]
        members: []
        tags:
          project: Project-2
      - name: Test
        deploymentTargetId: ""
        roles: ["Contributor"]
        members: []
        tags:
          project: Project-2
      - name: Prod
        deploymentTargetId: ""
        roles: ["Reader"]
        members: []
        tags:
          project: Project-2